from typing import Callable, Optional

class Bus:
    def __init__(self): ...
    def subscribe(self, channel: str, callback: Optional[Callable] = None, priority: Optional[int] = None) -> None: ...
    def publish(self, channel: str, *args: str, **kwargs: str) -> None: ...
