from typing import Any, Dict, Optional

class Tree:
    def __init__(self): ...
    def mount(self, root: object, script_name: str = '', config: Optional[Dict[str, Dict[str, Any]]] = None) -> None: ...
